### ISSUE TITLE
Send Email action not added?

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.emailapi#24]
https://civicrm.stackexchange.com/questions/25504/cant-install-extension-e-mail-api-1-17/25510

**Comment by lsh-0** [comment]
contents of that link: 
```
CiviCRM_API3_Exception: "Could not find the SQL file."

#0 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(190): civicrm_api3("Extension", "install", (Array:1))
#1 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(453): CRM_Admin_Form_Extensions->postProcess()
#2 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#8 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#9 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /home/domain/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /home/domain/public_html/wp-content/plugins/civicrm/civicrm.php(1246): CRM_Core_Invoke::invoke((Array:3))
#14 [internal function](): CiviCRM_For_WordPress->invoke("")
#15 /home/domain/public_html/wp-includes/class-wp-hook.php(286): call_user_func_array((Array:2), (Array:1))
#16 /home/domain/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters("", (Array:1))
#17 /home/domain/public_html/wp-includes/plugin.php(453): WP_Hook->do_action((Array:1))
#18 /home/domain/public_html/wp-admin/admin.php(224): do_action("toplevel_page_CiviCRM")
#19 {main}
Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred. Could not find the SQL file.
```
the important bit is: **Could not find the SQL file.**

there is a comment on the link mentioning that his has been fixed.

could we get a `1.17.1` release please?

**Comment by ErikHommel** [comment]
Done!

**Comment by lsh-0** [comment]
thanks, Erik
